### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by l0rinc**

### CODE REVIEW

**Comment by danieldietrich** [comment]
@zvozin feel free to review and merge PR's

**Comment by zvozin** [comment]
Thanks! Any license or code style concerns?


On April 10, 2017 at 10:57:30 AM, Daniel Dietrich (notifications@github.com)
wrote:

@zvozin <https://github.com/zvozin> feel free to review and merge PR's

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/javaslang/javaslang-kotlin/pull/1#issuecomment-292975320>,
or mute the thread

**Comment by danieldietrich** [comment]
Currently we release under the Apache 2.0 license (see [here](https://github.com/javaslang/javaslang/blob/master/LICENSE)).

We use IntelliJ IDEA and have a formatter that can be imported, see [idea-settings.jar](https://github.com/javaslang/javaslang/tree/master/.ide). But be careful - settings are defined IDE-wide, not project-wide.

Our source files have the typical Javaslang ascii-art headers.

You can add your name using the javadoc `@author` tag.

**Comment by danieldietrich** [comment]
Please take also a look at [CONTRIBUTING.md](https://github.com/javaslang/javaslang/blob/master/CONTRIBUTING.md) for some useful information on style...

**Comment by zvozin** [comment]
@danieldietrich @paplorinc when you have a second, please take a look. Used Gradle (Kotlin's IntelliJ integration really prefers it that way). What are the proper steps from here to a Maven repo release?

**Pull request merged**
